# Form implementation generated from reading ui file 'd:\Desktop\Dev\MadArtist\Ui\qt_ui\Entry_Main.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 500)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.OperationGroup = QtWidgets.QVBoxLayout()
        self.OperationGroup.setObjectName("OperationGroup")
        self.Open_Proj_Btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Open_Proj_Btn.setObjectName("Open_Proj_Btn")
        self.OperationGroup.addWidget(self.Open_Proj_Btn)
        self.Rename_Proj_Btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Rename_Proj_Btn.setObjectName("Rename_Proj_Btn")
        self.OperationGroup.addWidget(self.Rename_Proj_Btn)
        self.Remove_Proj_Btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Remove_Proj_Btn.setObjectName("Remove_Proj_Btn")
        self.OperationGroup.addWidget(self.Remove_Proj_Btn)
        self.gridLayout_2.addLayout(self.OperationGroup, 2, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.New_Proj_Btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.New_Proj_Btn.setObjectName("New_Proj_Btn")
        self.horizontalLayout.addWidget(self.New_Proj_Btn)
        self.Open_Project_Btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Open_Project_Btn.setObjectName("Open_Project_Btn")
        self.horizontalLayout.addWidget(self.Open_Project_Btn)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.DisplayLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.DisplayLabel.setObjectName("DisplayLabel")
        self.gridLayout_2.addWidget(self.DisplayLabel, 3, 0, 1, 1)
        self.ListDisplayList = QtWidgets.QListWidget(parent=self.centralwidget)
        self.ListDisplayList.setObjectName("ListDisplayList")
        self.gridLayout_2.addWidget(self.ListDisplayList, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
#        self.Rename_Proj_Btn.clicked.connect(MainWindow.RenameProj) # type: ignore
#        self.Open_Proj_Btn.clicked.connect(MainWindow.OpenProj) # type: ignore
#        self.Remove_Proj_Btn.clicked.connect(MainWindow.RemoveProj) # type: ignore
#        self.New_Proj_Btn.clicked.connect(MainWindow.CreateProj) # type: ignore
#        self.Open_Project_Btn.clicked.connect(MainWindow.OpenProjectWithPathDialog) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Open_Proj_Btn.setText(_translate("MainWindow", "打开"))
        self.Rename_Proj_Btn.setText(_translate("MainWindow", "重命名"))
        self.Remove_Proj_Btn.setText(_translate("MainWindow", "移除"))
        self.New_Proj_Btn.setText(_translate("MainWindow", "New Project"))
        self.Open_Project_Btn.setText(_translate("MainWindow", "Open project"))
        self.DisplayLabel.setText(_translate("MainWindow", "Version : Alpha_0.0.1"))

class Main(QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
